services:
  c:
    working_dir: /c

    #Container name
    container_name: c-container

    #Image to user
    image: c-image

    # Create build process
    build:
      context: .
      dockerfile: c.dockerfile

    # Map host port to docker port for developer container
    ports:
      - "8080:8080"
    
    # Mount directory to container directory
    volumes:
      - ./apps:/c/apps

    command: 
      tail -f /dev/null 